---
title: Vibe Debugging
author: tnwei
format:
  revealjs:
    center-title-slide: true
    theme: default
  html:
    code-fold: true
---

## {background-image=./talk_poster_buildclubkl2025.jpeg background-size=contain}

## When you vibe code

You are:

- Building features faster than you could think of
- In the zone
- Locked tf in

## But then, as your app gets complex ...

- You burn through more tokens debugging your app than building it
- AI stopped taking your instructions
- How can something so smart be so stupid?

## {.center}

Let's **vibe debug** your vibe'd code

## Who

- Nian Wei
- Tech @ Rosary Labs

## Dedication

This is for you if you want your best friend to code smarter

## 1. Do not roleplay {.center}

- No: This is so frustrating! How many times do I have you tell you that I want ... _(another two paragraphs)_
- Yes: Help me with this some more. I still see this error ...

## 2. Show your best friend what you see {.center}

::: {.notes}
Imagine sitting in a completely dark room. The only thing you have is a whatsapp chat where people ask you questions. Your friend is not an almighty god, it is an eager pupy with blindfolds.
Your best friend doesn't see what you see. It is guessing at what you see! Help it
:::
- No: It is not working!
- Yes: I am getting a 404 not found error


## 2. Show your best friend what you see {.center}

- Yes: I am getting a 404 not found error
- Very yes: I am getting a 404 not found error, pasting you the stacktrace below: ...

::: {.notes}
TODO: Show examples here from mine?
:::

## 3. Tell your best friend what you want {.center}

Be specific, don't be vague

- No: It is broken, please fix
- Yes: I want the div to be stacked vertically, not horizontally like it is now

## 3. Tell your best friend what you want {.center}

- (sigh), yes: Like I said earlier, I want the div to be stacked vertically. Now it is horizontal

You do have to repeat yourself sometimes

## 4. Tell your best friend what other things you have tried {.center}

Else your first few steps will be the same every time

- No: It doesn't work!!! 
- Yes: We have tried A and B and C, but we still get this 404 not found error

## {.center}

**Why do I have to type so much? Can't AI do this for me?** 

- Trains are not useful without train tracks
- Your best friend is not helpful without your direction!
- You have to steer your best friend
- You are free to let it go wherever it wants if you are willing to accept the outcome

## 5. Settle for information when you can't get answers {.center}

- No: _(after 5 tries)_ I still get 404 not found error!
- Yes: We still have 404 not found error, so change of plan. Can you explain how the previous methods are supposed to resolve them and think about why this current method is still not working?

## 6. Checkpoint your debugging, save your progress {.center}

- Yes: Give me a summary of everything we've spoke about thus far so that I can ask an expert
- Yes: Before we continue further, can you summarize the issue, the solutions tried thus far, the results, any relevant observations, and further thoughts?

## 7. Rollback your chat / start over if stuck {.center}

Going down a long convo when stuck is not helpful because:

- Tokens get expensive (token usage is a widening pyramid)
- LLMs are autoregressive, all previous text will shape their thought direction. Once distracted, stays distracted

## 8. Use multiple chats when needed {.center}

Keep your main convo focused, open a new one to ask for clarification.

:::{.notes}
You orchestrate and manage the context
Keep your conversation shorter for token cost reasons
Prevent from getting derailed when some topics are really big
:::

## 9. Google certain things yourself when stuck {.center}

- All the context is with you. You know best what is relevant or not. So your Googling is better than LLM web search
- Best friend's knowledge is outdated sometimes
- Lost on what to do with the Google results? See previous page ;)

:::{.notes}
Web search is fine for simple things. We are here if you are stuck.
Also saves tokens when your services are being billed by num messages
:::

## 10. Take time to understand the stacktrace yourself {.center}

Best way to find out:

- What to ask best friend
- How to avoid getting stuck

## 10. Take time to understand the stacktrace yourself {.center}

- You are the constant across all the tools you use
- You are the shared context across all of your tools
- Your memory lasts much longer
- You don't run out of tokens
- You are always online

## Tenets of vibe debugging {.smaller}

1. Do not roleplay
2. Show your best friend what you see
3. Tell your best friend what you want
4. Tell your best friend what other things you have tried
5. Settle for information when you can't get answers
6. Checkpoint your debugging, save your progress
7. Rollback your chat / start over if stuck
8. Use multiple chats when needed
9. Google certain things yourself when stuck
10. Take time to understand the stacktrace yourself

## {.center}

**If I'm typing and thinking so much anyway, maybe I am better off writing code myself**

- Yes at some point
- AI is good for getting new apps off the ground
- Maintaining apps with increasing complexity needs a lot of context and understanding
- ... that current gen AI doesn't have

## The serious skills behind vibe debugging {.center}

- Debugging itself is investigative journalism
- Vibe debugging is providing technical leadership to an AI detective sidekick

:::{.notes}
Most of the time the AI is doing the heavy lifting
You do the most important thing: decide
You decide what route to take
Sometimes you decide your sidekick is overwhelmed, and you choose to step in directly and debug it yourself
:::

These are actual serious skills to be a good coder

## {.center}

**Vibe coding might not make you a good coder, but vibe debugging will**

## Thanks for listening! {.center}

Vibe Debugging @ Build Club KL

bento.me/tnwei

<!-- 
Cutting floor

Run through examples of properly done debugging by various skill levels

- .env var is misspelt and thus seeing all sorts of errors, pusing satu bulatan barulah come back to find out what is going on
- simple mistake on chat apps repeating all the conversations instead of doing the 
- gnarly halfway code written and then ran out of credits where information needs to be passed from a game to another
-->
